#!/usr/bin/env bash
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
redirectsite= "/server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$redirectsite" /etc/nginx/sites_available/default
service nginx restart
