#!/usr/bin/env bash
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sudo sed -i "43i \\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" /etc/nginx/sites_available/default
service nginx restart
