#!/usr/bin/env bash
# This script install nginx, redirect to 301 Moved Permanently and restart:
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
redirect="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "/server_name _;/a $redirect" /etc/nginx/sites_available/default
sudo service nginx restart
