#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# - Configure HAproxy with version equal or greater than 1.5 so that it send traffic to web-01 and web-02
# - Distribute requests using a roundrobin algorithm
# - Make sure that HAproxy can be managed via an init script
# - Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.
# - For your answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements
sudo apt-get -y update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.6
sudo apt-get -y update
sudo apt-get install -y haproxy=1.6.\*
sudo tee -a /home/vagrant/sedpruebas/myload <<EOF
frontend http_front
   bind *:80
   mode http
   default_backend http_back

backend http_back
   balance roundrobin
   server 2805-web-01 34.139.28.87:80 check
   server 2805-web-02 54.164.112.178:80 check
EOF
sudo service haproxy start
