#!/usr/bin/env bash
# Script to fix nginx not listening on port 80 and kill nginx process.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
pkill -9 "$(cat /run/nginx.pid)"
