#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and:
# - Displays 4 and then bad luck from China for the 4th loop iteration.
# - Displays 9 and then bad luck from Japan for the 9th loop iteration.
# - Displays 17 and then bad luck from Italy for the 17th loop iteration.

count=1
endcount=20

while [ $count -le $endcount ]
do
	case $count in
	5)
	echo "bad luck from China"
	;;
	10)
	echo "bad luck from Japan"
	;;
	18)
	echo "bad luck from Italy"
	;;
	esac

	echo "$count"
	let count=$count+1
done
