#!/usr/bin/env bash
# This script configures an Ubuntu server with the below requirements.
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8.
# - This is running on Docker.
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i\8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
